CREATE TABLE `userData` (
	`port_id` INTEGER NOT NULL AUTO_INCREMENT,
	`nome` VARCHAR(255) NOT NULL,
	`papel` VARCHAR(32),
	`email` VARCHAR(64) NOT NULL UNIQUE,
	`interesses` VARCHAR(255) NOT NULL,
	`info` TEXT NOT NULL,
	PRIMARY KEY(`port_id`)
);

CREATE TABLE `skillsData` (
	`skills_id` INTEGER NOT NULL AUTO_INCREMENT,
	`lang` VARCHAR(128) NOT NULL,
	`lang2` VARCHAR(128) NOT NULL,
	`fworks` VARCHAR(128) NOT NULL,
	`tools` VARCHAR(128),
	PRIMARY KEY(`skills_id`)
);

CREATE TABLE `headerData` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`href` VARCHAR(128) NOT NULL UNIQUE,
	`titulo` VARCHAR(128) NOT NULL UNIQUE,
	PRIMARY KEY(`id`)
);

CREATE TABLE `resumeData` (
	`res_id` INTEGER NOT NULL AUTO_INCREMENT,
	`port_id` INTEGER NOT NULL,
	`skills_id` INTEGER NOT NULL,
	`telefone` VARCHAR(20) NOT NULL UNIQUE,
	`endereco` VARCHAR(255) NOT NULL,
	`cert` TINYTEXT NOT NULL,
	PRIMARY KEY(`res_id`),
	FOREIGN KEY(`port_id`) REFERENCES `userData`(`port_id`) ON DELETE CASCADE,
	FOREIGN KEY(`skills_id`) REFERENCES `skillsData`(`skills_id`) ON DELETE CASCADE
);